config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :categories, only: :show do 
  	resources :products, controller: :category_products, only: :show do 
      post 'add', on: :member
      resources :comments, controller: 'product_comments', only: :create
    end
    resources :comments, controller: 'category_comments', only: :create
  end
  resource :cart
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  namespace :admin do 
  	root 'index#index'
  	resources :categories
  	resources :users
  	resources :products do 
      post 'export', on: :collection
    end
    resources :orders, except: %i(new create)
  end
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
	root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items, dependent: :destroy
	has_many :items, through: :cart_items

	def empty?
		cart_items.empty?
	end

	def add_item(product)
		cart_item = cart_items.where(item: product).first_or_initialize
		cart_item.increment(:quantity)
		save && cart_item.save
	end

	def total
		cart_items.sum(&:subtotal)
	end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item, class_name: 'Product'

	def subtotal
		quantity * item.price
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	has_many :children, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
	belongs_to :parent, class_name: 'Category'
	validates_presence_of :name
	has_many :comments, as: :commentable
	acts_as_list scope: :parent

	scope :enabled, ->{ where(enabled: true)}
	scope :root, ->{ where(parent_id: nil)}
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
	validates_presence_of :name, :content
end

app/models/foreign_provider.rb
class ForeignProvider < Provider
	def full_address
		[street, city, state, zip_code, country].join(", ")
	end
end

app/models/local_provider.rb
class LocalProvider < Provider
	def full_address
		[country, city, street, zip_code].join
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items, dependent: :destroy
	has_many :change_records, class_name: 'OrderChangeRecord', dependent: :destroy
	validates_presence_of :name, :email, :amount
	accepts_nested_attributes_for :order_items, allow_destroy: true, reject_if: :all_blank

	after_save :record_changes

	def calculate_amount
		self.amount = order_items.sum(&:subtotal)
		self.save!
	end

	private

	def record_changes
		change_records.create(values: changes) if changed?
	end
end

app/models/order_change_record.rb
class OrderChangeRecord < ApplicationRecord
	belongs_to :order
	serialize :values
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product

	validates_presence_of :quantity, :price

	def subtotal
		quantity * price
	end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category, counter_cache: true
	has_many :cart_items, foreign_key: 'item_id', dependent: :destroy
	has_many :carts, through: :cart_items
	has_many :order_items, dependent: :destroy
	has_many :comments, as: :commentable
	belongs_to :provider
	validates_presence_of :name, :price

	scope :active, ->{ where(active: true).where('shelved_on <= ?', Date.current)}

	def to_param
		"#{id}-#{friendly_id}"
	end
end

app/models/provider.rb
class Provider < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
	before_action :find_order, only: %i(show edit update)
	def index 
		@orders = Order.page(params[:page])
	end

	def show
		@order_items = @order.order_items.includes(:product)
	end

	def edit 

	end

	def update
		if @order.update(order_params)
			@order.calculate_amount
			redirect_to admin_order_path(@order), notice: 'Updated Successfully!'
		else
			render :edit
		end
	end

	private

	def find_order
		@order = Order.find(params[:id])
	end

	def order_params
		params.require(:order).permit(:name, :email, :mobile, :paid,
			order_items_attributes: [:quantity, :product_id, :price, :_destroy, :id]
		)
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart = find_cart
		@cart_items = @cart.cart_items.includes(:item)
	end

	private

	def find_cart
		if session[:cart_id]
			Cart.find_by(id: session[:cart_id]) || Cart.new
		else
			Cart.new
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@categories = Category.enabled.root.all
		@products = Product.active.includes(:category).order('id desc').page(params[:page])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about

	end

	def contact

	end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_comments_helper.rb
module ProductCommentsHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for([:admin, @order]) do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class="form-group">
		<%= f.label :mobile %>
		<%= f.text_field :mobile %>
	</div>
	<div>
		<%= f.nested_fields_for :order_items do |ff| %>
			<%= ff.collection_select :product_id, Product.all, :id, :name %>
			<%= ff.number_field :quantity %>
			<%= ff.number_field :price %>
			<%= ff.remove_nested_fields_link 'Remove' %>
		<% end %>
		<%= f.add_nested_fields_link :order_items %>
	</div>
	<div class="form-group">
		<%= f.label :paid %>
		<%= f.check_box :paid %>
	</div>
	<div class="form-actions">
		<%= f.submit nil, class: 'btn btn-primary' %>
	</div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>編輯訂單</h1>
<%= render 'form' %>

app/views/admin/orders/index.html.erb
<h1>訂單管理</h1>

<table class="table">
	<thead>
		<tr>
			<th>編號</th>
			<th>訂購人</th>
			<th>信箱</th>
			<th>電話</th>
			<th>金額</th>
			<th>已付款</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @orders.each do |order| %>
			<tr>
				<td><%= order.id %></td>
				<td><%= order.name %></td>
				<td><%= order.email %></td>
				<td><%= order.mobile %></td>
				<td><%= number_to_currency order.amount %></td>
				<td><%= order.paid? %></td>
				<td><%= link_to '瀏覽', admin_order_path(order) %></td>
				<td><%= link_to '編輯', edit_admin_order_path(order) %></td>
				<td><%= link_to '刪除', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= paginate @orders %>

app/views/admin/orders/show.html.erb
<h1>瀏覽訂單 	<%= @order.id %></h1>
<%= link_to 'Back to Orders', admin_orders_path, class: 'btn btn-default' %>
<%= link_to 'Edit', edit_admin_order_path(@order), class: 'btn btn-success', data: { no_turbolink: true} %>
<ul>
	<li>姓名： <%= @order.name %></li>
	<li>信箱： <%= @order.email %></li>
	<li>電話： <%= @order.mobile %></li>
	<li>付款： <%= @order.paid? %></li>
	<li>總金額：<%= number_to_currency @order.amount %></li>
</ul>
<table class="table">
	<thead>
		<tr>
			<th>品名</th>
			<th>數量</th>
			<th>售價</th>
			<th>小計</th>
		</tr>
	</thead>
	<tbody>
		<% @order_items.each do |order_item| %>
			<tr>
				<td><%= order_item.product.name %></td>
				<td><%= order_item.quantity %></td>
				<td><%= number_to_currency order_item.price %></td>
				<td><%= number_to_currency order_item.subtotal %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h2>訂單資料修改記錄</h2>
<% @order.change_records.each do |record| %>
	<p>時間： <%= record.created_at %></p>
	<table class="table">
		<thead>
			<tr>
				<th>欄位</th>
				<th>原始值</th>
				<th>修改為</th>
			</tr>
		</thead>
		<tbody>
			<% record.values.each do |field, values| %>
				<tr>
					<td><%= field %></td>
					<td><%= values[0] %></td>
					<td><%= values[1] %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>