config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :categories, only: :show do 
  	resources :products, controller: :category_products, only: :show do 
      post 'add', on: :member
      resources :comments, controller: 'product_comments', only: :create
    end
    resources :comments, controller: 'category_comments', only: :create
  end
  resource :cart
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  namespace :admin do 
  	root 'index#index'
  	resources :categories
  	resources :users
  	resources :products do 
      post 'export', on: :collection
    end
    resources :orders, except: %i(new create)
  end
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
	root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items, dependent: :destroy
	has_many :items, through: :cart_items

	def empty?
		cart_items.empty?
	end

	def add_item(product)
		cart_item = cart_items.where(item: product).first_or_initialize
		cart_item.increment(:quantity)
		save && cart_item.save
	end

	def total
		cart_items.sum(&:subtotal)
	end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item, class_name: 'Product'

	def subtotal
		quantity * item.price
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	has_many :children, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
	belongs_to :parent, class_name: 'Category'
	validates_presence_of :name
	has_many :comments, as: :commentable
	acts_as_list scope: :parent

	scope :enabled, ->{ where(enabled: true)}
	scope :root, ->{ where(parent_id: nil)}
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
	validates_presence_of :name, :content
end

app/models/foreign_provider.rb
class ForeignProvider < Provider
	def full_address
		[street, city, state, zip_code, country].join(", ")
	end
end

app/models/local_provider.rb
class LocalProvider < Provider
	def full_address
		[country, city, street, zip_code].join
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items, dependent: :destroy
	has_many :change_records, class_name: 'OrderChangeRecord', dependent: :destroy
	validates_presence_of :name, :email, :amount
	accepts_nested_attributes_for :order_items, allow_destroy: true, reject_if: :all_blank

	after_save :record_changes

	def calculate_amount
		self.amount = order_items.sum(&:subtotal)
		self.save!
	end

	private

	def record_changes
		change_records.create(values: changes) if changed?
	end
end

app/models/order_change_record.rb
class OrderChangeRecord < ApplicationRecord
	belongs_to :order
	serialize :values
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product

	validates_presence_of :quantity, :price

	def subtotal
		quantity * price
	end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category, counter_cache: true
	has_many :cart_items, foreign_key: 'item_id', dependent: :destroy
	has_many :carts, through: :cart_items
	has_many :order_items, dependent: :destroy
	has_many :comments, as: :commentable
	belongs_to :provider
	validates_presence_of :name, :price

	scope :active, ->{ where(active: true).where('shelved_on <= ?', Date.current)}

	def to_param
		"#{id}-#{friendly_id}"
	end
end

app/models/provider.rb
class Provider < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

	def index
		@categories = Category.page(params[:page])
	end

	def new 
		@category = Category.new
	end

	def create
		@category = Category.new(category_params_permitted)
		if @category.save
			redirect_to admin_categories_path, notice: 'Created successfully!'
		else
			render :new
		end
	end

	def show 
		@category = Category.find(params[:id])
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params_permitted)
			redirect_to admin_category_path(@category), notice: 'Updated successfully!'
		else
			render :edit
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to admin_categories_path, alert: 'Category was deleted successfully!'
	end


	private


	def category_params_permitted
		params.require(:category).permit(:name, :description, :enabled)
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart = find_cart
		@cart_items = @cart.cart_items.includes(:item)
	end

	private

	def find_cart
		if session[:cart_id]
			Cart.find_by(id: session[:cart_id]) || Cart.new
		else
			Cart.new
		end
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@category = Category.enabled.find(params[:id])
		@products = @category.products.active.page(params[:page])
		@comments = @category.comments.includes(:user)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@categories = Category.enabled.root.all
		@products = Product.active.includes(:category).order('id desc').page(params[:page])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about

	end

	def contact

	end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_comments_helper.rb
module CategoryCommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_comments_helper.rb
module ProductCommentsHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div class="form-group">
		<%= f.label :enabled %>
		<%= f.check_box :enabled %>
	</div>
	<div class="form-actions">
		<%= f.submit nil, class: 'btn btn-primary' %>
	</div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>編輯類別</h1>
<%= link_to '回到類別首頁', admin_categories_path, class: 'btn btn-default'%>
<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1>類別管理</h1>

<%= link_to '新增類別' , new_admin_category_path, class: 'btn btn-default' %>

<table class="table">
	<thead>
		<tr>
			<th>編號</th>
			<th>名稱</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @categories.each do |category| %>
			<tr>
				<td><%= category.id%></td>
				<td><%= category.name %></td>
				<td><%= link_to '瀏覽', admin_category_path(category) %></td>
				<td><%= link_to '編輯', edit_admin_category_path(category) %></td>
				<td><%= link_to '刪除', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?'} %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= paginate @categories %>

app/views/admin/categories/new.html.erb
<h1>新增類別</h1>
<%= link_to '回到類別首頁', admin_categories_path, class: 'btn btn-default' %>
<%= render 'form' %>

app/views/admin/categories/show.html.erb
<h1>瀏覽類別</h1>
<%= link_to '回到類別首頁', admin_categories_path, class: 'btn btn-default' %>
<%= link_to '編輯', edit_admin_category_path(@category), class: 'btn btn-success' %>
<h2><%= @category.name %></h2>
<p><%= @category.description %></p>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<div class="row">
	<%= render partial: 'shared/products/product', collection: @products %>
</div>

<%=paginate @products %>
<div class="row">
	<div class="col-sm-6">
		<%= render 'shared/comments/form', url: category_comments_path(@category) if user_signed_in? %>
	</div>
	<div class="col-sm-6">
		<%= render 'shared/comments/list', comments: @comments %>
	</div>
</div>