config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :categories, only: :show do 
  	resources :products, controller: :category_products, only: :show do 
      post 'add', on: :member
      resources :comments, controller: 'product_comments', only: :create
    end
    resources :comments, controller: 'category_comments', only: :create
  end
  resource :cart
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  namespace :admin do 
  	root 'index#index'
  	resources :categories
  	resources :users
  	resources :products do 
      post 'export', on: :collection
    end
    resources :orders, except: %i(new create)
  end
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
	root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items, dependent: :destroy
	has_many :items, through: :cart_items

	def empty?
		cart_items.empty?
	end

	def add_item(product)
		cart_item = cart_items.where(item: product).first_or_initialize
		cart_item.increment(:quantity)
		save && cart_item.save
	end

	def total
		cart_items.sum(&:subtotal)
	end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item, class_name: 'Product'

	def subtotal
		quantity * item.price
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	has_many :children, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy
	belongs_to :parent, class_name: 'Category'
	validates_presence_of :name
	has_many :comments, as: :commentable
	acts_as_list scope: :parent

	scope :enabled, ->{ where(enabled: true)}
	scope :root, ->{ where(parent_id: nil)}
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
	validates_presence_of :name, :content
end

app/models/foreign_provider.rb
class ForeignProvider < Provider
	def full_address
		[street, city, state, zip_code, country].join(", ")
	end
end

app/models/local_provider.rb
class LocalProvider < Provider
	def full_address
		[country, city, street, zip_code].join
	end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items, dependent: :destroy
	has_many :change_records, class_name: 'OrderChangeRecord', dependent: :destroy
	validates_presence_of :name, :email, :amount
	accepts_nested_attributes_for :order_items, allow_destroy: true, reject_if: :all_blank

	after_save :record_changes

	def calculate_amount
		self.amount = order_items.sum(&:subtotal)
		self.save!
	end

	private

	def record_changes
		change_records.create(values: changes) if changed?
	end
end

app/models/order_change_record.rb
class OrderChangeRecord < ApplicationRecord
	belongs_to :order
	serialize :values
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product

	validates_presence_of :quantity, :price

	def subtotal
		quantity * price
	end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category, counter_cache: true
	has_many :cart_items, foreign_key: 'item_id', dependent: :destroy
	has_many :carts, through: :cart_items
	has_many :order_items, dependent: :destroy
	has_many :comments, as: :commentable
	belongs_to :provider
	validates_presence_of :name, :price

	scope :active, ->{ where(active: true).where('shelved_on <= ?', Date.current)}

	def to_param
		"#{id}-#{friendly_id}"
	end
end

app/models/provider.rb
class Provider < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :cart
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
		@cart = find_cart
		@cart_items = @cart.cart_items.includes(:item)
	end

	private

	def find_cart
		if session[:cart_id]
			Cart.find_by(id: session[:cart_id]) || Cart.new
		else
			Cart.new
		end
	end

end

app/controllers/category_products_controller.rb
class CategoryProductsController < ApplicationController
	before_action :find_category

	def show
		@product = @category.products.active.find(params[:id].to_i)
		viewed_at = cookies["view-product-#{@product.id}"].to_i
		puts viewed_at
		@viewed = viewed_at > @product.updated_at.to_i
		cookies["view-product-#{@product.id}"] = Time.now.to_i unless @viewed
	end

	def add
		@product = @category.products.active.find(params[:id].to_i)
		@cart = find_cart
		@cart.add_item(@product)
		session[:cart_id] = @cart.id
		redirect_back fallback_location: category_product_path(@product.category, @product)  , notice: '購物車已變更！'
	end

	private

	# Check it in`rails routes`
  # category_product GET /categories/:category_id/products/:id(.:format) category_products#show
 	def find_category
 		@category = Category.enabled.find(params[:category_id])
 	end

 	def find_cart
 		if session[:cart_id]
 			Cart.find_by(id: session[:cart_id]) || Cart.new
 		else
 			Cart.new
 		end
 	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@categories = Category.enabled.root.all
		@products = Product.active.includes(:category).order('id desc').page(params[:page])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about

	end

	def contact

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_products_helper.rb
module CategoryProductsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/category_products/show.html.erb
<div class="row">
	<div class="col-sm-6">
		<%= image_tag Faker::Placeholdit.image("640x640", "png", "333"),class: "pull-left img-responsive" %>
	</div>
	<div class="col-sm-6">
		<h1>
			<%= @product.name %>
			<small>
				<% if @viewed %>
					<br>
					你已經看過此商品囉！趕快購買吧！
				<% else %>

				<% end %>
			</small>
		</h1>
		<p>Category: <%=link_to @product.category.name, category_path(@product.category) %></p>
		<div class="product-description"><%= @product.description %></div>
		<div class="product-price"><%= number_to_currency @product.price %></div>
		<div class="product-content"><%= simple_format(@product.content)%></div>
		<div>
			<%= link_to '加到購物車' , add_category_product_path(@product.category, @product), method: :post, class: 'btn btn-primary' %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-6">
		<%= render 'shared/comments/form', url: category_product_comments_path(@product.category, @product) if user_signed_in? %>
	</div>
	<div class="col-sm-6">
		<%= render 'shared/comments/list', comments: @product.comments %>
	</div>
</div>

<% content_for :og do %>
	<meta property="og:locale" content="zh_TW"/>
  <meta property="og:site_name" content="shoppingcart-practice"/>
  <meta property="og:title" content="<%= @product.name %>"/>
  <meta property="og:url" content="<%= category_product_url(@product.category, @product) %>"/>
  <meta property="og:type" content="product"/>
  <meta property="og:updated_time" content="<%= @product.updated_at %>" />
  <meta property="og:description" content="<%= @product.description %>"/>
  <meta property="og:image" content=""/>
<% end %>